# Generated by Django 5.1.6 on 2025-03-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pdfFileLink',
        ),
        migrations.AddField(
            model_name='user',
            name='pdfFile',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
