version: "3.8"

services:
  django:
    build: 
      context: ./backend
    container_name: django_app
    command: >
      sh -c "cd /app/backend && python manage.py collectstatic --noinput && 
             gunicorn --reload --bind 0.0.0.0:8000 backend.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/backend/static
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: always

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always

  celery:
    build:
      context: ./backend
    container_name: celery_worker
    command: >
      sh -c "cd /app/backend && PYTHONPATH=/app/backend watchmedo auto-restart --patterns='*.py' --recursive -- celery -A backend.celery worker --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      - redis
      - django
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: always
  nextjs:
    build:
      context: ./frontend
    container_name: nextjs_app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    restart: always
    environment:
      - NODE_ENV=development

volumes:
  static_volume: